### ISSUE TITLE
There is a small error in this paper: the true mAP results are lower than reported

### ISSUE THREAD

**Issue by 4vik** [ParallelDots/generic-sku-detection-benchmark#2]
Caution: There is an error in the mAP evaluation script that this paper utilizes, which can be found under https://github.com/skrish13/SKU110K-evaluation .

You can see more about it in my comments here: https://github.com/skrish13/SKU110K-evaluation/issues/5

This leads to the issue that the mAP values here are actually reported to be a lot higher than they are in reality. In fact, the results of this method don't actually beat the results of Goldman's full approach, but are lower. 

For example, after fixing the above line of code, I get a true mAP on the GP-dataset of 0.234 instead of the reported mAP of 0.537. Can anyone reproduce this or am I missing something?

I still greatly appreciate the effort put in to labelling the Grocery product dataset etc. more finely, and I'm very greatful to be able to use those for research purposes!

Thanks again to @skrish13 and his team at ParallelDots.

**Comment by skrish13** [comment]
Hi, thanks for pointing this out! I have updated with correct results now :) 

While the method does not beat SOTA, I hope the extent of effectiveness of low data shown is useful. IMO it provides satisfactory results at standard IoU (0.5) while failing in higher IoUs. Eg: Our trainset consists of ~300 images from public domain (google images, OpenImages) with total of ~4500 annotations, while the training set of SOTA had ~1,200,000 annotations which is ~265x higher!
