### ISSUE TITLE
ShelfWise results, v1

### ISSUE THREAD

**Issue by rafalcycon** [ParallelDots/generic-sku-detection-benchmark#3]
Hey,

Thank you for hosting a leaderboard on this topic.

 As per the Leaderboard section in README we (ShelfWise.ai) would like to submit the results of our model:

| Dataset        | Method                        | AP        | AP<sup>.50</sup> | AP<sup>.75</sup> | AR<sub>300</sub> | AR<sup>.50</sup><sub>300</sub> |
| -------------- | ----------------------------- | --------- | ------------------ | ------------------ | ------------------ | ---------------------------------- |
| SKU110K-Test   | ShelfWise v1      | 0.529     | 0.892     | 0.583     | 0.598      | 0.926                                  |

The CSV file with our model's predictions is available here: https://drive.google.com/file/d/1rOr4E9koXGyEoLqGuRMuemmBMbbV2KdP/view

The method is an SSD with FPN (which also makes it significantly faster than Faster-RCNN), employed with a few mechanics that were developed to specifically tackle dense scenes that are common in retail. As of now we'd like to not disclose our methodology in full detail as it's still work-in-progress and remains in active research.

**Comment by skrish13** [comment]
Thanks for contributing! :) I've added it. Good to know that SSD works well. Just curious, was this trained on the SKU110K dataset?

PS for others: I double checked the results by using the csv and its correct :)

**Comment by rafalcycon** [comment]
Thank you! Glad you also added [Eran's results from their improved model](https://github.com/eg4000/SKU110K_CVPR19/issues/9). Btw. I would be grateful if you could change the reference (currently it's [3]) in our method's name - either to this issue or to our website www.shelfwise.ai ,due to lack of a better reference at this moment.

Yes, it was trained only on the SKU110K dataset.

**Comment by skrish13** [comment]
Oh it was supposed to be [4], my bad. Have changed it now (to this issue).

**Comment by rafalcycon** [comment]
Hey Sri,

We discovered a bug in our code :man_facepalming: . After fixing it and retraining the model, the following results are returned:

| Dataset        | Method                        | AP        | AP<sup>.50</sup> | AP<sup>.75</sup> | AR<sub>300</sub> | AR<sup>.50</sup><sub>300</sub> |
| -------------- | ----------------------------- | --------- | ------------------ | ------------------ | ------------------ | ---------------------------------- |
| SKU110K-Test   | ShelfWise v1      | 0.544     | 0.904     | 0.606     | 0.614      | 0.934                                  |

CSV: https://drive.google.com/file/d/1berCzA2cZ5SGmKuPohr73GUyBymlCLhC/view?usp=sharing

Apologies for the mix-up and for bothering you. We'd be grateful if you could update the results if you have a spare minute.

**Comment by skrish13** [comment]
No issues :) I have updated it now.

**Comment by rafalcycon** [comment]
Thank you!
